---
version: "1"
services:
  - type: web
    runtime: image
    plan: starter
    image: 
      url: docker.io/linuxserver/bookstack
    name: bookstack
    envVars:
      - key: PUID
        value: 1000
      - key: PGID
        value: 1000
      - key: APP_URL
        value: https://bookstack-om21.onrender.com
      - key: DB_HOST
        value: bookstack-db-66gf
      - key: DB_PORT
        # value: 3306
        value: 3306
      - key: DB_USER
        value: bookstack
      - key: DB_DATABASE
        value: bookstackapp
      - key: DB_PASS
        sync: false
      - key: PORT
        value: 6875:443
    disk:
      name: app_data
      mountPath: /config
  - type: web
    runtime: image
    plan: starter
    image:
      url: docker.io/linuxserver/mariadb
    name: bookstack_db
    envVars:
      - key: PUID
        value: 1000
      - key: PGID
        value: 1000
      - key: TZ
        value: Europe/London
      - key: MYSQL_DATABASE
        value: bookstackapp
      - key: MYSQL_USER
        value: bookstack
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: PORT
        value: 3306
    disk:
      name: db_data
      mountPath: /config
  - type: cron
    name: suspender
    runtime: go
    plan: starter
    schedule: "0 0 * * *"
    buildCommand: echo 'nobuild'
    startCommand: |
        curl --request POST \
        --url https://api.render.com/v1/services/srv-cjmmcivjbvhs73d1b900/suspend \
        --header "accept: application/json" \
        --header "authorization: $API_KEY" \
        && \
        curl --request POST \
        --url https://api.render.com/v1/services/srv-cjmmcivjbvhs73d1b8ug/suspend \
        --header "accept: application/json" \
        --header "authorization: $API_KEY" \
    envVars:
      - key: API_KEY
        sync: false
  - type: cron
    name: resumer
    runtime: go
    plan: starter
    schedule: "0 7 * * *"
    buildCommand: echo 'nobuild'
    startCommand: |
        curl --request POST \
        --url https://api.render.com/v1/services/srv-cjmmcivjbvhs73d1b900/resume \
        --header "accept: application/json" \
        --header "authorization: $API_KEY" \
        && \
        curl --request POST \
        --url https://api.render.com/v1/services/srv-cjmmcivjbvhs73d1b8ug/resume \
        --header "accept: application/json" \
        --header "authorization: $API_KEY" \
    envVars:
      - key: API_KEY
        sync: false
