---
version: "1"
services:
  - type: web
    runtime: image
    plan: starter
    image: 
      url: docker.io/linuxserver/bookstack
    name: bookstack
    envVars:
      - key: PUID
        value: 1000
      - key: PGID
        value: 1000
      - key: APP_URL
        value: https://bookstack-om21.onrender.com
      - key: DB_HOST
        value: bookstack-db-66gf
      - key: DB_PORT
        # value: 3306
        value: 3306
      - key: DB_USER
        value: bookstack
      - key: DB_DATABASE
        value: bookstackapp
      - key: DB_PASS
        sync: false
      - key: PORT
        value: 6875:443
    disk:
      name: app_data
      mountPath: /config
    # volumes: 
    #   - ./bookstack_app_data:/config
    # ports:
    #   - 6875:80
    # restart: unless-stopped
    # depends_on:
    #   - bookstack_db
  - type: web
    runtime: image
    plan: starter
    image:
      url: docker.io/linuxserver/mariadb
    name: bookstack_db
    envVars:
      - key: PUID
        value: 1000
      - key: PGID
        value: 1000
      - key: TZ
        value: Europe/London
      - key: MYSQL_DATABASE
        value: bookstackapp
      - key: MYSQL_USER
        value: bookstack
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: PORT
        value: 3306
    # volumes:
    #   - ./bookstack_db_data:/config
    disk:
      name: db_data
      mountPath: /config
    # restart: unless-stopped
